### PR TITLE
Set up views for app

### PR DESCRIPTION
**Pull request by lizzkats**

### CODE REVIEW

**Comment by Moniarchy** [comment]
@primeXXIX please add yourself to prr at prrr.learnersguild.org so that I can assign myself to this PR. Also @primeXXIX @lizzkats I see that this has already been merged and deleted already. Does this mean you don't want a review on it anymore?

**Comment by lizzkats** [comment]
@moniarchy- I do want a review I just usually merge my commits and implement feedback on the next commit so that I don't have merge conflicts

**Comment by Moniarchy** [comment]
I'd definitely recommend getting a review before merging so that the work you do for a particular branch really stays specific to that one branch. Either way, still super happy to give a review, but can your teammate log into prrr so I can self assign myself as a reviewer?

**Comment by lizzkats** [comment]
I will remind him when he's back :) Thanks Monica

**Pull request merged**
